mysite/blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [
    # example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    # example: /blog/post/ (same as /blog/)
    path('', views.PostLV.as_view(), name='post_list'),
    # example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),
    # example: /blog/archive/
    path('archive/',  views.PostAV.as_view(), name='post_archive'),
    # example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    # example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    # example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    # example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
]

mysite/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV,BookmarkDV


app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import BookmarkLV, BookmarkDV
from blog.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse  # url 패턴을 만들어주는 함수


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)  # 생성 시간
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)  # 수정 시간

    class Meta:
        verbose_name = 'post'  # 단수별칭
        verbose_name_plural = 'posts'  # 복수별칭
        db_table = 'blog_posts'  # 테이블이름(Default='blog_post')
        ordering = ('-modify_dt',)  # 'modify_dt' 기준 내림차순 정렬

    def __str__(self):  # 객체를 문자열로 표현
        return self.title

    def get_absolute_url(self):  # 이 메소드가 정의된 객체를 지칭하는 url 반환
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):  # 최신 포스트 반환
        return self.get_previous_by_modify_dt()

    def get_next(self):  # -modify_dt 기준 예전 포스트 반환
        return self.get_next_by_modify_dt()

mysite/bookmark/models.py
from django.db import models
from django.urls import reverse 

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

mysite/blog/views.py
from re import template
from statistics import mode
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post

class HomeView(TemplateView):
    template_name = 'home.html'

class PostLV(ListView): 
    model = Post 
    template_name = 'blog/post_all.html' 
    context_object_name = 'posts'  # 컨텍스트 변수명 = posts(디폴트: object_list)
    paginate_by = 2  # 한 페이지에 보여주는 객체 리스트 숫자 2

class PostDV(DetailView):  # DetailView: 테이블로부터 특정 객체를 가져와 상세정보 출력
    model = Post  

class PostAV(ArchiveIndexView):  # ArchiveIndexView: 테이블로부터 객체 리스트를 가져와 날짜 필드를 기준으로 최신 객체 출력
    model = Post  
    date_field = 'modify_dt'  

class PostYAV(YearArchiveView):  # YearArchiveView: 테이블로부터 날짜 필드 연도를 기준으로 객체리스트를 가져와 그 객체들이 속한 월을 출력
    model = Post  
    date_field = 'modify_dt'  
    make_object_list = True  # True 면 해당 연도에 해당하는 객체의 리스트를 만들어서 템플릿에 넘겨줌

class PostMAV(MonthArchiveView): # MonthArchiveView: 테이블로부터 날짜 필드 연월을 기준으로 객체리스트 출력
    model = Post  
    date_field = 'modify_dt'  

class PostDAV(DayArchiveView):  # DayArchiveView: 테이블로부터 날짜 필드 연월일을 기준으로 객체리스트 출력
    model = Post  
    date_field = 'modify_dt'  

class PostTAV(TodayArchiveView):  # TodayArchiveView: 테이블로부터 오늘을 기준으로 객체리스트 출력
    model = Post 
    date_field = 'modify_dt' 

mysite/bookmark/views.py
from re import template
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

mysite/blog/templates/blog/post_all.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/style.css'%}" />
        <title>Title</title>
    </head>
<body>
    <h1>MOODY</h1>

    {% for post in posts %}
        <div>
            <button class="title" onclick="location.href='{{ post.get_absolute_url }}'">{{post.title}}</button>
            <br>
        {{ post.modify_dt|date:"N d, Y" }}  
        <p>{{ post.description }}</p>  <!-- description 속성값 출력 -->
        </div>
        {% endfor %}
    <br> 
    <div class="contents">  <!-- 컨텐츠 분할 요소 -->
        <span>  <!-- span 태그 내의 줄은 같은 줄에 배치, 페이징 기능을 위한 줄 -->
            {% if page_obj.has_previous %}
            <!-- 장고의 page 객체가 들어있는 context variable, 현재 페이지 기준 이전 페이지 있는지 확인 -->
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
                <!-- page_obj.previous_page_number=이전 페이지 번호, PreviousPage에 url 연결 -->
            {% endif %}

            Page {{ page.obj.number }} of {{ page_obj.paginator.num_pages }}
            <!-- page_obj.number=현재 페이지 번호, page_obj.paginator.num_pages=총 페이지 개수 -->
            {% if page_obj.has_text %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            <!-- page_obj.next_page_number=다음 페이지 번호, NextPage에 url 연결 -->
            {% endif %}
    </div>


</body>
</html>

mysite/blog/templates/blog/post_archive.html
<h1>Post Archives until {% now "N d Y" %}</h1> <!-- now는 현재시간을 원하는 포멧으로 출력-->
<ul> <!-- unordered list, 순서없는 리스트-->
    {% for date in date_list %}
    <!-- date_list Context Variable은 DateQuerySet 객체 리스트(객체의 날짜 정보만을 추출)를 담고있음 -->
    <li style="display: inline;"> <!-- 한줄에 보여주는 태그 -->
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year{{date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {% for post in object_list %} <!-- Default context Variable, latest도 가능 -->
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        <!-- strong 태그는 볼드체 표시 -->
        {% endfor %}
    </ul>
</div>

mysite/blog/templates/blog/post_archive_day.html
<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

mysite/blog/templates/blog/post_archive_month.html
<h1>Post Archive for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="[[ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

mysite/blog/templates/blog/post_archive_year.html
<h1>Post Archive for {{ year|date: "Y": }}</h1>  <!-- year 컨텍스트 변수는 해당 연도에 대한 datetime.date 타입의 객체 -->

<ul>  <!-- 순서없는 리스트 -->
    {% for date in date_list %}
    <li style="display: inline";>  <!-- li style을 inline으로 지정 -->
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date: 'b' %}">
            {{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {%  endfor %}
    </ul>
</div>

mysite/blog/templates/blog/post_detail.html
<h2>{{ object.title }}</h2>

<p>{{ object.modify_dt|date:"j F Y"}}</p> <!-- 객체의 modify_dt 속성값을 "j F Y" 포맷으로 출력 -->
<br>

<div>
    {{ object.content|linebreaks }}  <!-- ₩n(newline)을 인식하게 함 -->
</div>

<p> 
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}"title="View previous post">
        &laquo;-- {{ object.get_previous }} 
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
    {{ object.get_next }}  --&raquo;
    <!-- get_next는 modify_dt 기준 다음 객체 반환, get_absolute_url은 다음 객체를 지칭하는 url 패턴 반환 -->
    </a>
    {% endif %}
</p>

mysite/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>

<head>
    <title>Django Bookmark Detail</title>
</head>

<body>

    <div id="content">
        <h1>{{ object.title }}</h1>
        <ul>
            <li>URL:<a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
    </div>
</body>

</html>

mysite/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>

<head>
    <title>Django Bookmark List</title>
</head>

<body>

    <div id="content">

        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Django WebProgramming{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% block extra-style %}{% endblock %}
</head>

<body style="padding-top: 90px;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <span class="navbar-brand mx-5 mb-0 font font-weight-bold font-italic">Django - Python Web Programming</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
                    </li>
                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container bg-warning">
        {% block content %}{% endblock %}
    </div>

    {% block footer %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    {% block extra-script %}{% endblock %}
</body>

</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block title %}home.html{% endblock %}

{% block content %}
<h4>This is CONTENT area.</h4>
{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-info"><h4>This is FOOTER area.</h4></footer>
{% endblock %}